# Generated by Django 2.2 on 2022-03-22 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20220322_2225'),
        ('product', '0002_product_product_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
