# Generated by Django 2.2 on 2022-05-18 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('author', models.CharField(default='', max_length=255)),
                ('publisher', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BookItem',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='item.Item')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookitem.Book')),
            ],
            bases=('item.item',),
        ),
    ]
